-- MySQL Script generated by MySQL Workbench
-- Wed Dec 17 13:29:35 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema portfolio_jeff
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio_jeff
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio_jeff` DEFAULT CHARACTER SET utf8 ;
USE `portfolio_jeff` ;

-- -----------------------------------------------------
-- Table `portfolio_jeff`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_jeff`.`projects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `img_url` VARCHAR(255) NULL,
  `github_url` VARCHAR(255) NULL,
  `published_at` DATE NULL,
  `updated_at` DATE NULL,
  `type` VARCHAR(45) NOT NULL,
  `is_active` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_jeff`.`technology`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_jeff`.`technology` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portfolio_jeff`.`projects_has_technology`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio_jeff`.`projects_has_technology` (
  `projects_id` INT NOT NULL,
  `technology_id` INT NOT NULL,
  PRIMARY KEY (`projects_id`, `technology_id`),
  INDEX `fk_projects_has_technology_technology1_idx` (`technology_id` ASC) ,
  INDEX `fk_projects_has_technology_projects_idx` (`projects_id` ASC) ,
  CONSTRAINT `fk_projects_has_technology_projects`
    FOREIGN KEY (`projects_id`)
    REFERENCES `portfolio_jeff`.`projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_technology_technology1`
    FOREIGN KEY (`technology_id`)
    REFERENCES `portfolio_jeff`.`technology` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
